services:
  web:
    image: ghcr.io/djchen/opencode-web-docker
    ports:
      - 8080:8080
    environment:
      SERVER_1_HOST: web1.opencode.example.com
      SERVER_1_BACKEND: https://api1.opencode.example.com
      SERVER_1_NAME: Server 1
      SERVER_1_APP_TITLE: OpenCode Server 1
      SERVER_2_HOST: web2.opencode.example.com
      SERVER_2_BACKEND: https://api2.opencode.example.com
      SERVER_2_NAME: Server 2
      SERVER_2_APP_TITLE: OpenCode Server 2
