import type { RuntimeConfigDeps, SyncStatus, SyncStatusInfo, ServerHttpInfo, ServerListItem, ServerState, SyncClientDeps } from "./types"
import { initSettingsSync } from "./sync-client"

// These globals are set by the preamble generated by entrypoint.sh
// They are accessible via `window` in the browser
declare const serverUrl: string
declare const serverName: string
declare const serverUsername: string
declare const serverPassword: string
declare const appTitle: string
declare const settingsSyncUrl: string
declare const settingsSyncInterval: string
declare const settingsSyncAuthHeader: string
declare const settingsSyncUsername: string
declare const settingsSyncPassword: string

const defaultServerUrlKey = "opencode.settings.dat:defaultServerUrl"
const serverStoreKey = "opencode.global.dat:server"

function normalizeUrl(url: unknown): string {
  if (typeof url !== "string") return ""
  const trimmed = url.trim()
  if (!trimmed) return ""
  return trimmed.replace(/\/+$/, "")
}

function extractUrl(item: unknown): string {
  if (typeof item === "string") return normalizeUrl(item)
  if (item && typeof item === "object") {
    const obj = item as Record<string, unknown>
    if (obj.type === "http" && obj.http && typeof (obj.http as Record<string, unknown>).url === "string") {
      return normalizeUrl(((obj.http as Record<string, unknown>).url as string))
    }
    if (typeof obj.url === "string") return normalizeUrl(obj.url)
  }
  return ""
}

export function initRuntimeConfig(deps?: Partial<RuntimeConfigDeps>): void {
  const d: RuntimeConfigDeps = {
    localStorage: deps?.localStorage ?? localStorage,
    document: deps?.document ?? document,
    location: deps?.location ?? location,
    window: deps?.window ?? (window as Window & typeof globalThis),
    console: deps?.console ?? console,
  }

  try {
    if (appTitle && typeof d.document === "object" && d.document) {
      d.document.title = appTitle
    }

    const raw = d.localStorage.getItem(serverStoreKey)
    let state: ServerState | null = null
    try {
      state = JSON.parse(raw || "null") as ServerState | null
    } catch {
      state = null
    }

    if (!state || typeof state !== "object" || Array.isArray(state)) {
      d.console.warn("OpenCode runtime-config: server store is not an object")
      state = { list: [], projects: {}, lastProject: {} }
    }

    if (!Array.isArray(state.list)) {
      d.console.warn("OpenCode runtime-config: server store list is not an array")
      state.list = []
    }
    if (!state.projects || typeof state.projects !== "object") {
      d.console.warn("OpenCode runtime-config: server store projects is not an object")
      state.projects = {}
    }
    if (!state.lastProject || typeof state.lastProject !== "object") {
      d.console.warn("OpenCode runtime-config: server store lastProject is not an object")
      state.lastProject = {}
    }

    const sUrl = serverUrl
    if (!sUrl) {
      d.console.warn("OpenCode runtime-config: serverUrl is not set, skipping runtime config")
      return
    }
    const currentOrigin = normalizeUrl(d.location.origin)
    let preservedMatch: ServerListItem | null = null

    for (let i = 0; i < state.list.length; i++) {
      const item = state.list[i]!
      const itemUrl = extractUrl(item)
      if (itemUrl === sUrl && !preservedMatch && typeof item === "object" && item !== null) {
        preservedMatch = item as ServerListItem
      }
    }

    const serverHttp: ServerHttpInfo = { url: sUrl }
    const serverObj: ServerListItem = { type: "http", http: serverHttp }

    if (preservedMatch && typeof preservedMatch === "object") {
      if (typeof preservedMatch.displayName === "string") serverObj.displayName = preservedMatch.displayName
      if (preservedMatch.http && typeof preservedMatch.http === "object") {
        if (typeof preservedMatch.http.username === "string") serverHttp.username = preservedMatch.http.username
        if (typeof preservedMatch.http.password === "string") serverHttp.password = preservedMatch.http.password
      }
    }
    if (serverName) serverObj.displayName = serverName
    if (serverUsername) serverHttp.username = serverUsername
    if (serverPassword) serverHttp.password = serverPassword

    const nextList: ServerListItem[] = [serverObj]

    for (let i = 0; i < state.list.length; i++) {
      const item = state.list[i]!
      const itemUrl = extractUrl(item)
      if (itemUrl === sUrl) continue
      if (itemUrl === currentOrigin && currentOrigin !== sUrl) continue
      nextList.push(item as ServerListItem)
    }

    const nextState: ServerState = {
      list: nextList,
      projects: state.projects,
      lastProject: state.lastProject,
    }
    const nextStateRaw = JSON.stringify(nextState)

    if (raw !== nextStateRaw) {
      d.localStorage.setItem(serverStoreKey, nextStateRaw)
    }

    const currentDefault = d.localStorage.getItem(defaultServerUrlKey)
    if (currentDefault !== sUrl) {
      d.localStorage.setItem(defaultServerUrlKey, sUrl)
    }

    ;(d.window as unknown as Record<string, unknown>).__OPENCODE_SERVER_URL = sUrl

    if (settingsSyncUrl) {
      const syncDeps: Partial<SyncClientDeps> = {
        localStorage: d.localStorage,
        document: d.document,
        window: d.window,
        console: d.console,
        fetch: d.window.fetch?.bind(d.window) ?? fetch.bind(globalThis),
        setTimeout: d.window.setTimeout?.bind(d.window) ?? setTimeout.bind(globalThis),
        clearTimeout: d.window.clearTimeout?.bind(d.window) ?? clearTimeout.bind(globalThis),
        setInterval: d.window.setInterval?.bind(d.window) ?? setInterval.bind(globalThis),
        clearInterval: d.window.clearInterval?.bind(d.window) ?? clearInterval.bind(globalThis),
        MutationObserver: d.window.MutationObserver ?? MutationObserver,
      }
      initSettingsSync(
        settingsSyncUrl,
        settingsSyncInterval,
        settingsSyncAuthHeader,
        settingsSyncUsername,
        settingsSyncPassword,
        syncDeps,
      )
    }
  } catch (error) {
    d.console.warn("Failed to apply OpenCode runtime config", error)
  }
}

export { extractUrl, defaultServerUrlKey, serverStoreKey }